# Generated by Django 5.2.6 on 2025-09-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('კაცი', 'kaci'), ('ქალი', 'qali'), ('ბავშვი', 'bavSvebi')], max_length=10, unique=True),
        ),
    ]
