# Generated by Django 5.2.6 on 2025-09-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('კაცი', 'Men'), ('ქალი', 'Women'), ('ბავშვი', 'Kids')], max_length=10, unique=True),
        ),
    ]
