# Generated by Django 5.2.6 on 2025-09-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Men', 'კაცი'), ('Women', 'ქალი'), ('Kids', 'ბავშვი')], max_length=10, unique=True),
        ),
    ]
