# Generated by Django 5.2.6 on 2025-09-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('კაცი', 'კაცი'), ('ქალი', 'ქალი'), ('ბავშვი', 'ბავშვი')], max_length=10, unique=True),
        ),
    ]
