# Generated by Django 5.2.6 on 2025-09-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
