# Generated by Django 5.2.6 on 2025-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True),
        ),
    ]
