# Generated by Django 5.2.6 on 2025-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_color_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=50),
        ),
    ]
