# Generated by Django 5.2.6 on 2025-10-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_category_options_remove_category_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
