# Generated by Django 5.2.6 on 2025-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_name_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='value_tr',
            field=models.CharField(blank=True, null=True),
        ),
    ]
