# Generated by Django 5.2.6 on 2025-10-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_attributevalue_value_tr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='stock',
            new_name='stock_main',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_shop',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
