# Generated by Django 5.2.6 on 2025-10-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_stock_productvariant_stock_main_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
