# Generated by Django 5.2.6 on 2025-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
