# Generated by Django 5.2.6 on 2025-11-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_productvariant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='products.productvariant'),
        ),
    ]
