# Generated by Django 5.2.6 on 2025-11-25 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_productimage_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
        ),
    ]
