# Generated by Django 5.2.6 on 2025-09-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
