# Generated by Django 5.2.6 on 2025-10-02 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_address_address_type_remove_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='mail@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
