# Generated by Django 5.2.6 on 2025-10-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_address_postal_code_address_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='session_key',
            field=models.CharField(blank=True, help_text='For anonymous address before login', max_length=40, null=True),
        ),
    ]
